### ISSUE TITLE
往下滑动奔溃

### ISSUE THREAD

**Issue by StarAndRainbow** [lihangleo2/smartVpageAdapterlibrary#2]
version:2.1.1
场景往下滑动加载数据的时候，不必现
奔溃日志：
java.lang.IllegalStateException: Design assumption violated.
	at androidx.viewpager2.adapter.FragmentStateAdapter.placeFragmentInViewHolder(FragmentStateAdapter.java
	at androidx.viewpager2.adapter.FragmentStateAdapter.onViewAttachedToWindow(FragmentStateAdapter.java:27
	at androidx.viewpager2.adapter.FragmentStateAdapter.onViewAttachedToWindow(FragmentStateAdapter.java:67
	at androidx.recyclerview.widget.RecyclerView.dispatchChildAttached(RecyclerView.java:7867)
	at androidx.recyclerview.widget.RecyclerView$5.addView(RecyclerView.java:893)
	at androidx.recyclerview.widget.ChildHelper.addView(ChildHelper.java:107)
	at androidx.recyclerview.widget.RecyclerView$LayoutManager.addViewInt(RecyclerView.java:8902)
	at androidx.recyclerview.widget.RecyclerView$LayoutManager.addView(RecyclerView.java:8860)
	at androidx.recyclerview.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1647)
	at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1591)
	at androidx.recyclerview.widget.LinearLayoutManager.scrollBy(LinearLayoutManager.java:1395)
	at androidx.recyclerview.widget.LinearLayoutManager.scrollVerticallyBy(LinearLayoutManager.java:1136)
	at androidx.recyclerview.widget.RecyclerView.scrollStep(RecyclerView.java:1972)
	at androidx.recyclerview.widget.RecyclerView.scrollByInternal(RecyclerView.java:2071)
	at androidx.recyclerview.widget.RecyclerView.onTouchEvent(RecyclerView.java:3531)
	at androidx.viewpager2.widget.ViewPager2$RecyclerViewImpl.onTouchEvent(ViewPager2.java:991)
	at android.view.View.dispatchTouchEvent(View.java:15121)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3165)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2833)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3171)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2847)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3171)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2847)
	at com.scwang.smart.refresh.layout.SmartRefreshLayout.dispatchTouchEvent(SmartRefreshLayout.java:913)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3171)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2847)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3171)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2847)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3171)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2847)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3171)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2847)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3171)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2847)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3171)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2847)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3171)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2847)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3171)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2847)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3171)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2847)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3171)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2847)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3171)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2847)
	at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:567)
	at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1918)
	at android.app.Activity.dispatchTouchEvent(Activity.java:4344)
	at androidx.appcompat.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:69)
	at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:515)
	at android.view.View.dispatchPointerEvent(View.java:15398)
	at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:6978)
	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:6735)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:6186)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:6248)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:6209)
	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:6379)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:6217)
	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:6436)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:6190)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:6248)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:6209)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:6217)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:6190)
	at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:9385)
	at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:9336)
	at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:9290)
	at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:9536)
	at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:281)
	at android.view.InputEventReceiver.nativeConsumeBatchedInputEvents(Native Method)
	at android.view.InputEventReceiver.consumeBatchedInputEvents(InputEventReceiver.java:261)
	at android.view.ViewRootImpl.doConsumeBatchedInput(ViewRootImpl.java:9477)
	at android.view.ViewRootImpl$ConsumeBatchedInputRunnable.run(ViewRootImpl.java:9630)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1412)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1420)
	at android.view.Choreographer.doCallbacks(Choreographer.java:1047)
	at android.view.ChoreographerExtImpl.checkScrollOptSceneEnable(ChoreographerExtImpl.java:434)
	at android.view.Choreographer.doFrame(Choreographer.java:918)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1395)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:240)
	at android.os.Looper.loop(Looper.java:351)
	at android.app.ActivityThread.main(ActivityThread.java:8423)

17:26:55.492  1416-1416  DEBUG                                                        E  	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:584)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1013)
Back traces ends.

**Comment by StarAndRainbow** [comment]
升级了2.1.2，目前没有重现到。应该是数据一样，导致getItemId是一样的导致的
